version: '3'
services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
    ports:
      - 4200:4200
    volumes:
      - ./frontend:/user/src/app/frontend
      - /usr/src/app/frontend/node_modules
  backend:
    container_name: backend
    restart: always
    build:
      context: ./backend
    ports: 
      - "9100:9100" 
    volumes:
      - ./backend:/usr/src/app/backend
      - /usr/src/app/backend/node_modules
    links:
      - database
  database:
    container_name: database_mongodb
    build:
      context: ./database
    ports:
      - 27017:27017
    logging:
      driver: none
    volumes:
      - ./mongodb:/data/db
  